# Generated by Django 3.2.16 on 2022-11-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='goodschannel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goodschannel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='spu',
        ),
        migrations.RemoveField(
            model_name='skuimage',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='skuspecification',
            name='option',
        ),
        migrations.RemoveField(
            model_name='skuspecification',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='skuspecification',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='specificationoption',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='spuspecification',
            name='spu',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
        migrations.DeleteModel(
            name='GoodsChannel',
        ),
        migrations.DeleteModel(
            name='GoodsChannelGroup',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.DeleteModel(
            name='SKUImage',
        ),
        migrations.DeleteModel(
            name='SKUSpecification',
        ),
        migrations.DeleteModel(
            name='SpecificationOption',
        ),
        migrations.DeleteModel(
            name='SPU',
        ),
        migrations.DeleteModel(
            name='SPUSpecification',
        ),
    ]
