# Generated by Django 3.2.16 on 2022-11-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_rename_default_image_sku_default_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_image_url',
            new_name='default_image',
        ),
    ]
