# Generated by Django 3.2.16 on 2022-11-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_rename_default_image_url_sku_default_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_image',
            new_name='default_image_url',
        ),
    ]
