# Generated by Django 3.2.16 on 2022-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_rename_default_image_sku_default_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='default_image_url',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='默认图片'),
        ),
    ]
