# Generated by Django 4.1.3 on 2022-11-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_areas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
    ]
