# Generated by Django 3.2.16 on 2022-11-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221123_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
