# Generated by Django 3.2.16 on 2022-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='小计'),
        ),
    ]
